#!/usr/bin/env python3
"""Generate docs/style-gallery.html from the DOM the running app emits.

The gallery used to be a hand-written copy of the views' markup, and it
drifted far enough that a review pass examined states the app no longer
produced. This reads the real thing instead: build a debug binary (which
includes src/domdump.rs), drive the app to each state you want, and every
screen change prints its `.app` subtree to the console.

    xcrun simctl launch --console-pty booted com.goosemobile.app > /tmp/applog.txt
    ...drive the app...
    scripts/capture-gallery.py /tmp/applog.txt

A run REPLACES the gallery. Keeping states you did not visit is how the old
hand-written gallery went stale in the first place — a screen captured on
another branch survives every later run, `docs/audit.js` keeps reporting it
clean, and nothing ever says the markup no longer exists. Pass --merge if you
really do want to build the set up over several runs; it names every key it
carries over so a stale one cannot pass unnoticed.
"""

from __future__ import annotations

import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GALLERY = ROOT / "docs" / "style-gallery.html"
STORE = ROOT / "docs" / "gallery-states.json"

# key -> the label the gallery shows. Keys come from `Destination::key` in
# src/nav.rs — the same table the app navigates by, so a screen that is not in
# it is a screen the gallery never sees.
LABELS = {
    "chats": "Chats",
    "chat": "Chat transcript",
    "code-list": "Code sessions",
    "code-new": "New code session",
    "code-chat": "Code agent transcript",
    "code-diff": "Code review",
    "code-pulls": "Pull requests",
    "extensions": "Extensions",
    "extensions-detail": "Extension detail",
    "skills": "Skills",
    "skill": "Skill detail",
    "settings": "Settings",
}

HEAD = (
    '<meta charset="utf-8">'
    '<meta name="viewport" content="width=device-width, initial-scale=1, '
    'maximum-scale=1, viewport-fit=cover">'
    '<link rel="stylesheet" href="../assets/main.css">'
)

PAGE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>goose mobile — style gallery</title>
<style>
  /* Gallery chrome only. Nothing here reaches inside a frame: each state is
     an <iframe srcdoc>, so no font, colour or inherited property crosses the
     boundary and what you see is the app's own stylesheet doing all of it. */
  body {{
    margin: 0;
    padding: 24px;
    background: #8a8a8a;
    font: 13px -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    color: #fff;
  }}
  h1 {{ margin: 0 0 4px; font-size: 18px; font-weight: 600; }}
  .note {{ margin: 0 0 24px; max-width: 62ch; opacity: 0.85; line-height: 1.5; }}
  .grid {{ display: flex; flex-wrap: wrap; gap: 24px; }}
  .cell {{ width: 402px; }}
  .label {{ margin-bottom: 6px; font-weight: 600; }}
  .shell {{
    width: 402px; height: 874px; border-radius: 44px; overflow: hidden;
    box-shadow: 0 10px 30px rgb(0 0 0 / 0.35);
  }}
  iframe.gallery-frame {{ width: 402px; height: 874px; border: 0; display: block; }}
</style>
</head>
<body>
<h1>goose mobile — style gallery</h1>
<p class="note">
  <strong>Generated, not written.</strong> Every frame below is the real
  <code>.app</code> subtree captured out of the running app by
  <code>src/domdump.rs</code> and written here by
  <code>scripts/capture-gallery.py</code>. Do not edit this file by hand — a
  hand-maintained copy is what drifted from the app last time. Each frame is a
  402×874 viewport (iPhone 17 Pro) linking <code>../assets/main.css</code>, so
  the styling is exactly what ships. Frames render in whichever colour scheme
  your OS is set to; check both.
</p>
<p class="note">
  Safe-area insets are zero here — a browser has no notch — so the floating
  chrome sits higher than it does on a device. Positions are not what this is
  for; colour, type, spacing and state are.
</p>
<div class="grid">
{cells}
</div>
</body>
</html>
"""

CELL = """  <div class="cell">
    <div class="label">{label}</div>
    <div class="shell">
      <iframe class="gallery-frame" title="{label}" width="402" height="874"
              srcdoc="{srcdoc}"></iframe>
    </div>
  </div>"""


def main() -> int:
    args = [a for a in sys.argv[1:] if a != "--merge"]
    merge = "--merge" in sys.argv
    log = Path(args[0] if args else "/tmp/applog.txt")
    if not log.exists():
        print(f"no console log at {log}", file=sys.stderr)
        return 1

    previous: dict[str, str] = {}
    if STORE.exists():
        previous = json.loads(STORE.read_text())

    text = log.read_text(errors="replace")
    found = re.findall(r"@@DOM@@(.*?)@@(.*?)@@ENDDOM@@", text, re.DOTALL)
    states: dict[str, str] = {}
    for key, markup in found:
        if markup.strip():
            states[key] = markup.strip()

    carried = sorted(set(previous) - set(states))
    if merge:
        for key in carried:
            states[key] = previous[key]
        if carried:
            print(
                "carried over from a previous run (NOT captured now, may be "
                f"stale): {', '.join(carried)}",
                file=sys.stderr,
            )
    elif carried:
        print(f"dropped (not visited this run): {', '.join(carried)}", file=sys.stderr)

    if not states:
        print("no DOM dumps in the log — is this a debug build?", file=sys.stderr)
        return 1

    STORE.write_text(json.dumps(states, indent=1, sort_keys=True))

    order = list(LABELS)
    ordered = [k for k in order if k in states] + [
        k for k in sorted(states) if k not in order
    ]
    cells = "\n".join(
        CELL.format(
            label=html.escape(LABELS.get(key, key)),
            srcdoc=html.escape(
                f"<!doctype html><html lang=en><head>{HEAD}</head>"
                f"<body>{states[key]}</body></html>",
                quote=True,
            ),
        )
        for key in ordered
    )
    GALLERY.write_text(PAGE.format(cells=cells))
    print(
        f"{GALLERY.relative_to(ROOT)}: {len(ordered)} states "
        f"({', '.join(ordered)}); {len(found)} dumps read"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
